[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  API_KEY_PRODIA = "aFsgFlKcpTHmFG98cd3i"  # Você pode definir variáveis de ambiente aqui, se necessário.
