[build]
  functions = "functions"  # A pasta onde estão suas funções serverless

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # Redireciona as rotas para as funções serverless
  status = 200

[build.environment]
  YOUTUBE_API_KEY = "AIzaSyAfb29L9WVbJcJVGnqK0L9-hdIaIO0bxAM"
