[build]
  functions = "netlify/functions"
  command = "npm run build"  # Se necessário, caso você use algum comando de build

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[build.environment]
  YOUTUBE_API_KEY = "AIzaSyAj0uMyoj89SX-6d8AG6NRE5PZu6RLgCAw"
